version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my-network
    #network_mode: host

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_OPTIONS='{"useUnifiedTopology":true}'
    command: sh -c "sleep 30 && node app"
    depends_on:
      - mongo
    networks:
      - my-network
  #network_mode: host

  caching-service:
    build:
      context: ./nest-caching-service
      dockerfile: dockerfile
    environment:
      - PORT=5000
      - MS=3001
    ports:
      - "5000:5000"
      - "3001:3001"
    networks:
      - my-network
    #network_mode: host
    restart: always

  storing-service:
    build:
      context: ./nest-storing-service
      dockerfile: dockerfile
    environment:
      - DB_URI=mongodb://mongo:27017/mydatabase
      - MS_PORT=3003
      - PORT=4000
    ports:
      - "4000:4000"
      - "3003:3003"
    networks:
      - my-network
    #network_mode: host
    depends_on:
      - mongo
    restart: always

  whatsapp-service:
    build:
      context: ./nest-whatsapp-service
      dockerfile: dockerfile
    networks:
      - my-network
    ports:
      - "3000:3000"
    #network_mode: host
    environment:
      - PORT=3000
      - PORT_CACHING=3001
      - PORT_CACHING_TWO=3002
      - PORT_STORING=3003
    depends_on:
      - mongo
      - storing-service
      #- caching-service

networks:
  my-network:
    external: false
